#!/usr/bin/env python3
from __future__ import annotations

import re
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
FIPS_ROOT = Path("/home/ubuntu/src/fips")
LINK_RS = FIPS_ROOT / "src/protocol/link.rs"
MMP_MOD_RS = FIPS_ROOT / "src/mmp/mod.rs"
OUT_RS = REPO_ROOT / "crates/microfips-core/src/generated/fips_compat.rs"


LINK_ENUMS = {
    "LinkMessageType": "LINK_MSG",
    "DisconnectReason": "DISC_REASON",
}

MMP_CONSTS = [
    "SENDER_REPORT_BODY_SIZE",
    "RECEIVER_REPORT_BODY_SIZE",
    "SENDER_REPORT_WIRE_SIZE",
    "RECEIVER_REPORT_WIRE_SIZE",
]


def parse_enum_values(text: str, enum_name: str) -> dict[str, str]:
    m = re.search(rf"pub enum {enum_name}\s*\{{(?P<body>.*?)\n\}}", text, re.S)
    if not m:
        raise RuntimeError(f"could not find enum {enum_name}")
    body = m.group("body")
    values: dict[str, str] = {}
    for variant, value in re.findall(r"^\s*([A-Za-z0-9_]+)\s*=\s*(0x[0-9A-Fa-f]+|\d+)\s*,", body, re.M):
        values[variant] = value
    return values


def parse_pub_const_values(text: str, names: list[str]) -> dict[str, str]:
    out: dict[str, str] = {}
    for name in names:
        m = re.search(rf"pub const {name}: [^=]+ = ([^;]+);", text)
        if not m:
            raise RuntimeError(f"could not find const {name}")
        out[name] = m.group(1).strip()
    return out


def render() -> str:
    link_text = LINK_RS.read_text()
    mmp_text = MMP_MOD_RS.read_text()

    blocks: list[str] = []
    for enum_name, prefix in LINK_ENUMS.items():
        for variant, value in parse_enum_values(link_text, enum_name).items():
            const_name = f"{prefix}_{re.sub(r'(?<!^)(?=[A-Z])', '_', variant).upper()}"
            blocks.append(f"pub const {const_name}: u8 = {value};")

    mmp_values = parse_pub_const_values(mmp_text, MMP_CONSTS)
    for name, value in mmp_values.items():
        blocks.append(f"pub const {name}: usize = {value};")

    body = "\n".join(sorted(blocks))
    return f"// @generated by tools/generate_fips_compat.py from upstream FIPS. DO NOT EDIT.\n// Source: {LINK_RS}\n// Source: {MMP_MOD_RS}\n\n{body}\n"


def main() -> None:
    if not LINK_RS.exists() or not MMP_MOD_RS.exists():
        raise SystemExit("upstream FIPS source files not found")
    OUT_RS.parent.mkdir(parents=True, exist_ok=True)
    OUT_RS.write_text(render())
    print(f"wrote {OUT_RS}")


if __name__ == "__main__":
    main()
