// Integration test for golden cross-implementation vectors.
// Vectors are generated by fips-golden-gen in Amperstrand/fips
// and validated here to prove secp256k1 (C binding) ↔ k256 (pure Rust) compatibility.

#[path = "vector_types.rs"]
mod vector_types;

#[test]
fn golden_vectors_file_not_yet_generated() {
    let _ = core::mem::size_of::<vector_types::VectorFile>();
}
